export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const GET_M_DATA_SUCCESS = "GET_M_DATA_SUCCESS";

export const GET_DATA_SET_LIST = "GET_DATA_SET_LIST";
export const GET_DATA_SET_LIST_SUCCESS = "GET_DATA_SET_LIST_SUCCESS";
export const GET_DATA_SET_LIST_FAILURE = "GET_DATA_SET_LIST_FAILURE";

export const GET_FIELD_LIST = "GET_FIELD_LIST";
export const GET_FIELD_LIST_SUCCESS = "GET_FIELD_LIST_SUCCESS";
export const GET_FIELD_LIST_FAILURE = "GET_FIELD_LIST_FAILURE";

export const GET_LOG_DATA = "GET_LOG_DATA";
export const GET_LOG_DATA_SUCCESS = "GET_LOG_DATA_SUCCESS";
export const GET_LOG_DATA_FAILURE = "GET_LOG_DATA_FAILURE";

export const GET_STATUS = "GET_STATUS";
export const GET_SESSION_ID_SUCCESS = "GET_SESSION_ID_SUCCESS";
export const GET_SESSION_ID_FAILURE = "GET_SESSION_ID_FAILURE";

export const QUERY_SUCCESS = "QUERY_SUCCESS";
export const QUERY_FAILURE = "QUERY_FAILURE";